### ISSUE TITLE
difference from http://pdfgrep.sourceforge.net/

### ISSUE THREAD

**Issue by johnyf** [x2b/pdfgrep#1]
The readme could offer more information on whether this is the same or a different tool, from the one of the same name [here](http://pdfgrep.sourceforge.net/), that is also distributed with MacPorts.

**Comment by x2b** [comment]
Well, the two projects are not at all related. This was more of a weekend project for me, I haven't looked at it for long time, though I am hesitant to _officially_ abandon it.

**Comment by johnyf** [comment]
Thanks for the clarification.
